### PR TITLE
Protect access to policiesCanceller using a mutext

### LINKED ISSUE #1738: Unenrollment timeout monitor can crash with concurrent access panic
- Version: 8.3.2, likely earlier releases too
- Operating System: Linux
- Steps to Reproduce: Not sure yet

There are cases where the unenrollment scheduler can cause a concurrent write or concurrent read and write error, causing Fleet Server to panic and crash with logs like:

```
fatal error: concurrent map writes\n
{0xc000533b30, ...}, ...}, ...)\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/src/github.com/elastic/fleet-server/internal/pkg/coordinator/monitor.go
{{{0xc00046f3e0, 0x14}, 0x0, 0x0}, 0x1, {0xc000a05500, 0x28cf, 0x2a80}, 0x0,
:211 +0x39c fp=0xc000d836c8 sp=0xc000d83660 pc=0x5645d5fd569c\ngithub.com/elastic/fleet-server/v7/internal/pkg/coordinator.(*monitorT).rescheduleUnenroller(0xc00000ed20, {0x5645d6fb7b58, 0xc0000cc380}, 0xc000d83fa0, 0xc000d83f28)\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/src/github.com/elastic/fleet-server/internal/pkg/coordinator/monitor.go:413 +0x4c9 fp=0xc000d83b08 sp=0xc000d836c8 pc=0x5645d6b32e69\ngithub.com/elastic/fleet-server/v7/internal/pkg/coordinator.(*monitorT).ensureLeadership.func1(
\ngoroutine 222 [running]:\nruntime.throw({0x5645d6b87588, 0x10})\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/.gvm/versions/go1.17.9.linux.amd64/src/runtime/panic.go:1198 +0x71 fp=0xc000d83660 sp=0xc000d83630 pc=0x5645d5ff8111\nruntime.mapassign_faststr(0x5645d6fb7b58, 0xc0000cc380, {0xc000533b30, 0x24})\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/.gvm/versions/go1.17.9.linux.amd64/src/runtime/map_faststr.go
created by github.com/elastic/elastic-agent-client/v7/pkg/client.(*client).actionRoundTrip\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/pkg/mod/github.com/elastic/elastic-agent-client/v7@v7.0.0-20210922110810-e6f1f402a9ed/pkg/client/client.go:467 +0x245\n\ngoroutine 131 [select
/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/pkg/mod/google.golang.org/grpc@v1.43.0/stream.go:333 +0x98\ncreated by google.golang.org/grpc.newClientStreamWithParams\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/pkg/mod/google.golang.org/grpc@v1.43.0/stream.go:332 +0xb45\n\n
\ngoroutine 127 [select]:\ngoogle.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc000132120)\n\t
, 0xc0000cfaa0})\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/frame.go:237 +0x6e\n
0xc000169180, 0x0)\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/.gvm/versions/go1.17.9.linux.amd64/src/crypto/tls/conn.go:606 +0x112\ncrypto/tls.(*Conn).readRecord
bytes.(*Buffer).ReadFrom(0xc0001693f8, {0x5645d6fa1f00, 0xc000014108})\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/.gvm/versions/go1.17.9.linux.amd64/src/bytes/buffer.go:
, 0xc000176005, 0x2f})\n\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/.gvm/versions/go1.17.9.linux.amd64/src/net/fd_posix.go:56 +0x29\n
\t/var/lib/jenkins/workspace/ger_fleet-server-package-mbp_8.3/.gvm/versions/go1.17.9.linux.amd64/src/internal/poll/fd_unix.go:167 +0x25a\nnet.(*netFD).Read(0xc0001c1500, {0xc000176000
:363 +0xa5\n\ngoroutine 124 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fc8f8c69fb8, 0x72
...
```

See full logs here [fleet-server stderr.txt](https://github.com/elastic/fleet-server/files/9315991/fleet-server.stderr.txt)
 

This may explain some of the recent issues we've seen in Cloud with Fleet Server mysteriously crashing. We just now finally have logs to explain this.

There are several reads and writes to the `policies` and `policiesCanceller` maps in https://github.com/elastic/fleet-server/blob/7a1372a42e6079d065002b7d034ab83fde0ff69c/internal/pkg/coordinator/monitor.go#L77-L78

These are done in various, interacting go routines inside this file. We likely need to coordinate across these routines using channels rather than via shared memory to avoid this problem. [Race detector](https://go.dev/blog/race-detector) may be helpful here.

Though https://github.com/elastic/fleet-server/pull/1605 made some changes in this area, we've been seeing crashes from Fleet Server before this change. It's unclear whether or not this change caused the problem or not.

### PR DESCRIPTION
**Pull request by ph**
## What is the problem this PR solves?

There were a race condition possible with between the enrolling goroutine and the main coordinator routine. I've added a mutex to protect the access of the `policiesCanceller` and audited the remaining part of the code. Everything else are executed in the same goroutine (via channel's select) so the `policies` field is unaffected. But, I think the code would benefit to be `cleanup` and the _policies_ and the _policiesCanceller_  field to be consolidated in a single field AND moving the manipulation the values either using channel or via methods on the struct. I've initially looked to refactor the code, but I would clearly have taking more time. Looking a the panic described in #1738 the critical field field would be the _policiesCanceller_.

## Checklist

~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #1738
- Relates #1739

### CODE REVIEW

**Comment by ph** [comment]
I want to have a reproducible unit test here, but the test suite doesn't covert that yet.

File: internal/pkg/coordinator/monitor.go [hunk 1]
```diff
@@ -74,8 +74,10 @@ type monitorT struct {
 	leadersIndex  string
 	agentsIndex   string
 
-	policies          map[string]policyT
-	policiesCanceller map[string]context.CancelFunc
+	policies map[string]policyT
+
+	muPoliciesCanceller sync.Mutex
+	policiesCanceller   map[string]context.CancelFunc
```
Comment (michel-laterman) [inline internal/pkg/coordinator/monitor.go:80]: I know that an integration test checks the size of this attribute, hopefully it's not an issue

**Review by michel-laterman — APPROVED** [review]

File: internal/pkg/coordinator/monitor.go (hunk 1 above)
Comment (ph) [reply internal/pkg/coordinator/monitor.go:80]: oh, let me take a look, that seems like a bad pattern in that case.

**Comment by ph** [comment]
valid failure in the integration suite on local system.. :(

**Comment by ph** [comment]
I've created https://github.com/elastic/fleet-server/issues/1744 as a more long term concerning the refactoring with a few observation I've made looking into the code.

File: internal/pkg/coordinator/monitor_integration_test.go [hunk 2]
```diff
@@ -347,7 +347,7 @@ func TestMonitorUnenrollerSetAndClear(t *testing.T) {
 	assert.True(t, agent.Active)
 	// Make sure canceller is no longer there
 	assert.Len(t, pm.(*monitorT).policies, 1)
-	assert.Len(t, pm.(*monitorT).policiesCanceller, 0)
+	assert.Equal(t, pm.(*monitorT).ActivePoliciesCancellerCount(), 0)
```
Comment (ph) [inline internal/pkg/coordinator/monitor_integration_test.go:350]: I attest this is a bit ugly, but the code is structured in a way where internal state is both accessed in the test suite and also on goroutine. I've created a specific issues to cover some of the problem https://github.com/elastic/fleet-server/issues/1744

I've took some time last week to create a unit test that could possibly trigger that, but I think this is more a problem in the way the code is structured and how it manages the internal goroutine.
