### PR TITLE
Policy changes can be dropped during policy rollouts to large number …

### LINKED ISSUE #522: A policy that is updated frequently in a large fleet may not be updated.
fleet-server 7.14  8fc011454055c1ed9f8f2c5a21a9dd12b07ddf68

Steps to reproduce:

0) Configure Fleet-Server to support 5k endpoints or higher.
1) Use Horde to enroll 5k endpoints.
2) Change the policy every 30 seconds.

Result:  The first policy change will be rolled out, but the following changes will be ignored.   The policy will appear stuck.

### PR DESCRIPTION
**Pull request by scunningham**
…of agents.  Aggregates changes to avoid missing updates.

## What does this PR do?

Works around race condition where internal notifications on policy update were dropped.

## Why is it important?

Policies can appear stuck at scale.

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] I have made corresponding change to the default configuration files
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Follow instructions in related issue.  Check the logs.  

## Related issues

- Closes #522 

## Logs

```
10:53:08.821 INF Received hits on local monitor ctx="policy agent monitor" nHits=1 service.name=fleet-server
10:53:09.052 INF Received hits on local monitor ctx="policy agent monitor" nHits=1 service.name=fleet-server
10:54:44.821 INF policy rollout end coordinatorIdx=1 ctx="policy agent monitor" policyId=d43cd250-df22-11eb-9c07-7d2f0052b4b7 revisionIdx=18 service.name=fleet-server tdiff=99004.626266
10:54:44.822 INF Hits dispatched to main loop ctx="policy agent monitor" nHits=2 service.name=fleet-server
10:54:44.823 INF policy revised ctx="policy agent monitor" ncoord=1 nrev=19 ocoord=1 orev=18 policyId=d43cd250-df22-11eb-9c07-7d2f0052b4b7 service.name=fleet-server
10:54:44.824 INF policy rollout begin coordinatorIdx=1 ctx="policy agent monitor" nSubs=4940 policyId=d43cd250-df22-11eb-9c07-7d2f0052b4b7 revisionIdx=19 service.name=fleet-server throttle=20
10:56:23.628 INF policy rollout end coordinatorIdx=1 ctx="policy agent monitor" policyId=d43cd250-df22-11eb-9c07-7d2f0052b4b7 revisionIdx=19 service.name=fleet-server tdiff=98801.968635
```

### CODE REVIEW

File: internal/pkg/policy/monitor.go [hunk 1]
```diff
@@ -128,6 +135,35 @@ LOOP:
...
+
+		for {
+			select {
+			case <-ctx.Done():
+				m.log.Info().Msg("Exit policy monitor local")
+				return
+			case nHits := <-outputCh:
+				m.log.Info().Int("nHits", len(nHits)).Msg("Received hits on local monitor")
+				hits = append(hits, nHits...)
+				outCh = localOutputCh
```
Comment (blakerouse) [inline internal/pkg/policy/monitor.go:155]: Why is `outCh` set in this case? Couldn't it be set at the top of the go func or just use `localOutputCh` directly. Or am I missing something about this flow.

**Review by blakerouse — APPROVED** [review]
Change looks good, just one comment on the flow of the channel in the go routine.

File: internal/pkg/policy/monitor.go (hunk 1 above)
Comment (scunningham) [reply internal/pkg/policy/monitor.go:155]: The localOutputCh  has no buffer by design.  If we use it directly it will block and we won't pickup any additional changes on outputCh.

We could make localOutpuCh a buffered channel, but how big is the buffer?  You may still hit the max size and block.  

This method allows us to continue to add data to the 'hits' array until the consuming loop is able to retrieve the data.  Switching 'outCh' to null once consumed allows the loop to spin properly until additional data is available.

File: internal/pkg/policy/monitor.go [hunk 2]
```diff
@@ -128,6 +135,35 @@ LOOP:
 	return nil
 }
 
+// Aggegates changes from the output channel until the main loop can process.
+func (m *monitorT) monitorOutputChannel(ctx context.Context, outputCh <-chan []es.HitT) chan []es.HitT {
```
Comment (aleksmaus) [inline internal/pkg/policy/monitor.go:139]: nit:
maybe?
```
func (m *monitorT) monitorOutputChannel(ctx context.Context, outputCh <-chan []es.HitT) <-chan []es.HitT {
```

**Review by aleksmaus — APPROVED** [review]
LGTM

File: internal/pkg/policy/monitor.go (hunk 1 above)
Comment (blakerouse) [reply internal/pkg/policy/monitor.go:155]: Thanks for the explanation. I missed the `outCh = nil` in the last case, that make sense now.

**Review by blakerouse — APPROVED** [review]
Looks good.

**Comment by urso** [comment]
Have we tried to reproduce it in a test putting the subsystem under pressure? Any test we should add here?
