### PR TITLE
Fix issues with config reloading

### LINKED ISSUE #691: Agent Mode restart on failure uses the wrong configuration
When Elastic Agent sends a new configuration to Fleet Server and that configuration fails to load, then Fleet Server will rollback to the very first configuration that Elastic Agent ever sent. So if Elastic Agent sent 5 configurations before the last bad one it would result it going back all the way to the 1st configuration not the 5th configuration.

Fleet Server should take the configuration from Elastic Agent as final, being that it should not rollback to a good configuration on its own. Only the Elastic Agent should have control of that behavior. Instead it should keep trying to use that last configuration.

There is also an issue where changing the `fleet.agent.id` and/or any settings in `output` will not result in Fleet Server actually reloading.

### PR DESCRIPTION
**Pull request by blakerouse**
## What is the problem this PR solves?

There are 3 problems that this PR solves:

1. Configurations changes to the `fleet.*` or the `output.*` sections of the Fleet configurations would not cause the Fleet Server to restart the required sections of the server for those changes to actually take affect.
2. In the case that the configuration change fails (maybe a transient elasticsearch connection problem) then the Fleet Server would roll all the way back to its initial configuration sent from Elastic Agent.
3. No integration tests existed for Fleet Server being controlled by Elastic Agent.

## How does this PR solve the problem?

This solves each problem as follows:

1. It adjusts the configuration change checking code to check for the `fleet.*` and `output.*` sections.
2. It always stores the last given configuration in the FleetServet struct so on restart it always goes back to the last configuration that Elastic Agent provided it.
3. Integration test was added.

This PR also has a side-effect change that I needed to make to get the `libbeat/v7/x-pack/elastic-agent/core/server` working (which controls the AgentMode, just like the real Elastic Agent does). It seems that the `ristretto` module that Fleet Server uses for caching registers global flags because it includes `golang/glog` and the `libbeat/v7/x-pack/elastic-agent/core/server` includes the `logp` from libbeat registering the same flag. So to get the integration tests working I had to remove the `ristretto` module only when running integration tests.

## How to test this PR locally

`make test-int`

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #691

### CODE REVIEW

File: cmd/fleet/main.go [hunk 1]
```diff
@@ -511,6 +511,7 @@ LOOP:
 		}
 
 		curCfg = newCfg
+		f.cfg = curCfg
```
Comment (aleksmaus) [inline cmd/fleet/main.go:514]: doesn't look like curCfg is used after this point

why not just do
```
f.cfg = newCfg
```

and remove 
```
curCfg = newCfg
```

File: internal/pkg/cache/impl.go [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+// or more contributor license agreements. Licensed under the Elastic License;
+// you may not use this file except in compliance with the Elastic License.
+
+package cache
+
+import (
+	"time"
+)
+
+type CacheImpl interface {
```
Comment (aleksmaus) [inline internal/pkg/cache/impl.go:11]: nit: maybe different name for the interface, having "Impl" in it a bit odd. 
```
type Cacher interface
```

**Review by aleksmaus — APPROVED** [review]

File: cmd/fleet/main.go (hunk 1 above)
Comment (blakerouse) [reply cmd/fleet/main.go:514]: it is used in the for loop for checking to see if the configuration change required a reload

Comment (aleksmaus) [reply cmd/fleet/main.go:514]: ughh, didn't notice the bigger loop it's in ... long function
