### PR TITLE
Replace all secret references in input map

### LINKED ISSUE #3083: Replace secret vars for arrays
When implementing replacement of secret vars in agent policies [here](https://github.com/elastic/fleet-server/pull/2863), we left out a scenario when the variables can have array values.

See thread [here](https://github.com/elastic/kibana/issues/154715#issuecomment-1792869195) for more info.

Expected fix: check if vars have array values, replace secrets in them.

To reproduce:

- Add `secret: true` to the [manifest](https://github.com/elastic/integrations/blob/main/packages/ti_otx/data_stream/threat/manifest.yml) locally:

```
      - name: api_token
        type: text
        title: API Token
        multi: false
        required: true
        show_user: true
        description: The Alienvault OTX API token
        secret: true
```

- Add AlienVault OTX integration and populate the API token/key.
- Enroll an agent and check the agent policy sent to the agent.
- The secrets in `request.transforms` should be replaced.

```
    streams:
      - id: httpjson-ti_otx.threat-a520c8d4-1c8e-48c6-8525-d046ab1b8bda
        data_stream:
          dataset: ti_otx.threat
          type: logs
        config_version: '2'
        interval: 5m
        request.method: GET
        request.tracer.filename: ../../logs/httpjson/http-request-trace-*.ndjson
        request.url: 'https://otx.alienvault.com/api/v1/indicators/export'
        request.timeout: 30s
        request.transforms:
          - set:
              target: header.Content-Type
              value: application/json
          - set:
              target: header.X-OTX-API-KEY
              value: '${SECRET_0}'
```

### PR DESCRIPTION
**Pull request by michel-laterman**
## What is the problem this PR solves?

Secret references are being missed as they can be embedded in sub objects or arrays as part of the input (or stream) object.

## How does this PR solve the problem?

Use a more generic approach to go through input objects and replace secret references.

## How to test this PR locally

`make test` for the unit test that was added.

Or follow the integration setup instructions in #3083 

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/fleet-server#changelog)

## Related issues

- Closes #3083

### CODE REVIEW

File: internal/pkg/policy/secret.go [hunk 1]
```diff
@@ -162,35 +176,8 @@ func processOutputSecret(ctx context.Context, output smap.Map, bulker bulk.Bulk)
...
-		} else {
-			newStream[streamKey] = streamVal
-		}
-	}
-	return newStream
-}
-
-// replace values mathing a secret ref regex, e.g. $co.elastic.secret{<secret ref>} -> <secret value>
-func replaceSecretRef(ref string, secretValues map[string]string) string {
+// replaceStringRef replaces values mathing a secret ref regex, e.g. $co.elastic.secret{<secret ref>} -> <secret value>
```
Comment (kpollich) [inline internal/pkg/policy/secret.go:179]:
```suggestion
// replaceStringRef replaces values matching a secret ref regex, e.g. $co.elastic.secret{<secret ref>} -> <secret value>
```

**Review by kpollich — APPROVED** [review]
Code + tests LGTM 🚀

**Review by juliaElastic — APPROVED** [review]
