### PR TITLE
Remove logger and timings from tests

### LINKED ISSUE #3134: TestCancelCtxChildBulker may be flaky
## Flaky Test

* **Test Name:** TestCancelCtxChildBulker.
* **Link:** [Link to file/line number in github](https://github.com/elastic/fleet-server/blob/main/internal/pkg/bulk/engine.go#L176).
* **Branch:** [buildkite build](https://buildkite.com/elastic/fleet-server/builds/2585#018c2148-cff9-4a20-8caf-3e01795801fb/946)
* **Notes:** It looks like the engine tries to log the `Bulker started` message after the test has exited, meaning that the output that the logger uses has been invalidated.

### Stack Trace

```
=== RUN   TestCancelCtxChildBulker
--
  | PASS: TestCancelCtxChildBulker (0.00s) | 1s
  | PASS
  | panic: Log in goroutine after TestCancelCtxChildBulker hengine.go:176: {"level":"debug","outputName":"remote","message":"Bulker started"}
  |  
  | goroutine 107 [running]:
  | testing.(*common).logDepth(0xc00040a000, {0xc0000c6600, 0x5f}, 0x3)
  | /opt/buildkite-agent/.gvm/versions/go1.21.4.linux.amd64/src/testing/testing.go:1022 +0x674
  | testing.(*common).log(...)
  | /opt/buildkite-agent/.gvm/versions/go1.21.4.linux.amd64/src/testing/testing.go:1004
  | testing.(*common).Logf(0xc00040a000, {0x147c7fd, 0xb}, {0xc000091100, 0x4, 0x4})
  | /opt/buildkite-agent/.gvm/versions/go1.21.4.linux.amd64/src/testing/testing.go:1055 +0x9a
  | github.com/rs/zerolog.TestWriter.Write({{0x7f239056b1b0?, 0xc00040a000?}, 0x7f239056a530?}, {0xc0000ba400, 0x43, 0x1f4})
  | /opt/buildkite-agent/go/pkg/mod/github.com/rs/zerolog@v1.31.0/writer.go:142 +0x448
  | github.com/rs/zerolog.LevelWriterAdapter.WriteLevel(...)
  | /opt/buildkite-agent/go/pkg/mod/github.com/rs/zerolog@v1.31.0/writer.go:27
  | github.com/rs/zerolog.(*Event).write(0xc0000cad90)
  | /opt/buildkite-agent/go/pkg/mod/github.com/rs/zerolog@v1.31.0/event.go:80 +0x2b3
  | github.com/rs/zerolog.(*Event).msg(0xc0000cad90, {0x147e38e, 0xe})
  | /opt/buildkite-agent/go/pkg/mod/github.com/rs/zerolog@v1.31.0/event.go:151 +0x3fe
  | github.com/rs/zerolog.(*Event).Msg(...)
  | /opt/buildkite-agent/go/pkg/mod/github.com/rs/zerolog@v1.31.0/event.go:110
  | github.com/elastic/fleet-server/v7/internal/pkg/bulk.(*Bulker).CreateAndGetBulker.func1.1()
  | /opt/buildkite-agent/builds/bk-agent-prod-gcp-1701363788573093291/elastic/fleet-server/internal/pkg/bulk/engine.go:176 +0xa5
  | github.com/elastic/fleet-server/v7/internal/pkg/bulk.(*Bulker).CreateAndGetBulker.func1()
  | /opt/buildkite-agent/builds/bk-agent-prod-gcp-1701363788573093291/elastic/fleet-server/internal/pkg/bulk/engine.go:180 +0xfd
  | created by github.com/elastic/fleet-server/v7/internal/pkg/bulk.(*Bulker).CreateAndGetBulker in goroutine 106
  | /opt/buildkite-agent/builds/bk-agent-prod-gcp-1701363788573093291/elastic/fleet-server/internal/pkg/bulk/engine.go:174 +0x832
  | FAIL	github.com/elastic/fleet-server/v7/internal/pkg/bulk	0.121s
```

### PR DESCRIPTION
**Pull request by michel-laterman**
## What is the problem this PR solves?

Tests are flaky

## How does this PR solve the problem?

Remove test logger that is being used after test terminates

## How to test this PR locally

`make test-unit`

## Related issues

- Closes #3134

### CODE REVIEW

File: internal/pkg/bulk/bulk_test.go [hunk 1]
```diff
@@ -255,8 +254,8 @@ func TestCancelCtx(t *testing.T) {
 	for _, test := range tests {
 		t.Run(test.name, func(t *testing.T) {
 			ctx, cancelF := context.WithCancel(context.Background())
-			ctx = testlog.SetLogger(t).WithContext(ctx)
```
Comment (michel-laterman) [inline internal/pkg/bulk/bulk_test.go:258]: Had to remove the test loggers from these tests as they were still being used after the test case terminated
